### ISSUE TITLE
Liste déroulante au lieu de champs texte si possible et valeurs par défaut

### ISSUE THREAD

**Issue by Ascris** [TheGuysBrushes/cofidur_gestion_formation#12]
Lorsqu'un élément est lié avec un autre, il serait préférable d'utiliser des listes déroulante au lieu de champs textes avec des id à rentrer, afin d'éviter les erreurs et que ce soit plus simple d'utilisation

**Comment by flodavid** [comment]
C'est en bonne voie, vérifier que c'est fait partout.

**Comment by flodavid** [comment]
Par contre, il faut voir pour mettre des valeurs par défaut des listes déroulantes

**Comment by flodavid** [comment]
Fait pour les dates par @Ascris, il reste à remplir les champs texte avec une valeur par défaut quand c'est possible et les listes déroulantes quand ce n'est pas des dates.
