### ISSUE TITLE
Affichage Javascript de la partie "Détails" de la formation d'Opérateur @Ascris

### ISSUE THREAD

**Issue by Ascris** [TheGuysBrushes/cofidur_gestion_formation#14]

**Comment by Ascris** [comment]
Done :ok_hand:

**Comment by flodavid** [comment]
A quoi ça correspond, est-ce fonctionnel et validé ?

**Comment by flodavid** [comment]
Suite à ma modifcation de la page operatorformation_show les détails et le bouton correspondant ne sont pas affichés correctement
