### ISSUE TITLE
AJOUTER LE RETOUR A LA FORMATION CORRESPONDANTE DANS task.html.twig

### ISSUE THREAD

**Issue by Ascris** [TheGuysBrushes/cofidur_gestion_formation#19]

**Comment by flodavid** [comment]
J'ai utilisé partout l'historique pour retourner à la page précédente. Ce n'est pas très propre, mais ça marche et c'est plus rapide, car la page est souvent stockée par les navigateurs. On garde tel quel ?

**Comment by Ascris** [comment]
Ce n'est pas très propre mais ça marche. C'est plus rapide car la page est souvent stockée par les navigateurs. :ok_hand:
Je trouve ça pas mal, c'est parfait pour le moment. Affaire classée.
